//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const background_png = "../assets/background.png";
export const logo_png = "../assets/logo.png";
export const logo_svg = "../assets/logo.svg";
export const OpenSans_CondBold_woff = "../assets/OpenSans-CondBold.woff";
export const OpenSans_CondBold_woff2 = "../assets/OpenSans-CondBold.woff2";
export const OpenSans_CondLight_woff = "../assets/OpenSans-CondLight.woff";
export const OpenSans_CondLight_woff2 = "../assets/OpenSans-CondLight.woff2";
export const ordinace_svg = "../assets/ordinace.svg";
export const zuby_png = "../assets/zuby.png";
