//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const OpenSans_CondBold_woff = "../assets/OpenSans-CondBold.woff";
export const OpenSans_CondBold_woff2 = "../assets/OpenSans-CondBold.woff2";
export const OpenSans_CondLight_woff = "../assets/OpenSans-CondLight.woff";
export const OpenSans_CondLight_woff2 = "../assets/OpenSans-CondLight.woff2";
export const background_png = "../assets/background.png";
export const button1_svg = "../assets/button1.svg";
export const button2_svg = "../assets/button2.svg";
export const logo_png = "../assets/logo.png";
export const logo_svg = "../assets/logo.svg";
export const ordinace_svg = "../assets/ordinace.svg";
export const right_column_1_jpg = "../assets/right_column_1.jpg";
export const right_column_2_jpg = "../assets/right_column_2.jpg";
export const telefon1_png = "../assets/telefon1.png";
export const telefon_png = "../assets/telefon.png";
export const telephoneGreen_png = "../assets/telephoneGreen.png";
export const zuby_png = "../assets/zuby.png";
